version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: always
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

  sqlc:
    image: sqlc/sqlc
    container_name: sqlc
    volumes:
      - .:/src
    command: 
      - generate
    working_dir: /src
    restart: always

volumes:
  postgresdb-data:
