// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  name,
  hash_password
) VALUES (
  $1, $2, $3
)
RETURNING name, email, hash_password, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	HashPassword string `json:"hashPassword"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE name = $1
`

func (q *Queries) DeleteUser(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteUser, name)
	return err
}

const getUser = `-- name: GetUser :one
SELECT name, email, hash_password, created_at, updated_at FROM users
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, name)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT name, email, hash_password, created_at, updated_at FROM users
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Name,
			&i.Email,
			&i.HashPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  set
  hash_password = $2
WHERE name = $1
RETURNING name, email, hash_password, created_at, updated_at
`

type UpdateUserParams struct {
	Name         string `json:"name"`
	HashPassword string `json:"hashPassword"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
